### PR TITLE
fix(ecvrf): add Debug impl to ECVRF struct

### LINKED ISSUE #5: Public types should implement Debug

### PR DESCRIPTION
**Pull request by mariocao**
Add `Debug` implementation to `ECVRF` structure.

Some of the `openssl` fields, such as `BigNumContext`, `ECCurve` and `MessageDigest` do not implement `Debug`. However they are not really important as this information is already included in the field `cipher_suite`. :smile: 

Closes #5

### CODE REVIEW

File: src/openssl/mod.rs [hunk 1]
```diff
@@ -72,7 +77,7 @@ pub enum Error {
     /// The `hash_to_point()` function could not find a valid point
     #[fail(display = "Hash to point function could not find a valid point")]
     HashToPointError,
-    /// The proof length is invalid
+    /// The proof lengthCould provide an issue description? is invalid
```
Comment (aesedepece) [inline src/openssl/mod.rs]: This does probably not belong here.

File: src/openssl/mod.rs [hunk 2]
```diff
@@ -109,8 +116,18 @@ pub struct ECVRF {
     qlen: usize,
     // 2n = length of a field element in bits rounded up to the nearest even integer
     n: usize,
-    // Cofactor of the curve
-    cofactor: u8,
+}
+
+impl Debug for ECVRF {
```
Comment (aesedepece) [inline src/openssl/mod.rs:121]: I support this implementation for the sake of not adding more dependencies to this library.

For what it's worth, there are a couple of crates providing macros that achieve the same goal of excluding some fields from the `struct` so the `Debug` implementation can be automatically `Derive`d:
- [debug_stub_derive](https://crates.io/crates/debug_stub_derive)
- [derivative](https://crates.io/crates/derivative)

**Review by aesedepece — CHANGES_REQUESTED** [review]

**Review by tmpolaczyk — APPROVED** [review]
Looks good to me

**Review by aesedepece — APPROVED** [review]
